<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mariuxi Maribel Tenesaca Yuqui">

<title>Análisis de un conjunto de datos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/clipboard/clipboard.min.js"></script>
<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/quarto.js"></script>
<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/popper.min.js"></script>
<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/anchor.min.js"></script>
<link href="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="TenesacaMariuxiAnálisis de un conjunto de datos_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis de un conjunto de datos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mariuxi Maribel Tenesaca Yuqui </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p><strong>Información del conjunto de datos:</strong></p>
<p>Las imágenes de las variedades de pasas Kecimen y Besni cultivadas en Turquía se obtuvieron con CVS. Se utilizaron un total de 900 granos de pasas, incluyendo 450 piezas de ambas variedades. Estas imágenes fueron sometidas a diversas etapas de pre-procesamiento y se extrajeron 7 características morfológicas.</p>
<p><strong>Información de atributos:</strong></p>
<p>Área: Da el número de píxeles dentro de los límites de la pasa.<br>
Perímetro: Mide el entorno calculando la distancia entre los límites de la pasa y los píxeles que la rodean.<br>
MajorAxisLength: Da la longitud del eje principal, que es la línea más larga que se puede dibujar en la pasa.<br>
MinorAxisLength: Da la longitud del eje pequeño, que es la línea más corta que se puede dibujar en la pasa.<br>
Excentricidad: Da una medida de la excentricidad de la elipse, que tiene los mismos momentos que las pasas.<br>
Área convexa: Da el número de píxeles de la cáscara convexa más pequeña de la región formada por la pasa.<br>
Extensión: Da la relación entre la región formada por la pasa y el total de píxeles en el cuadro delimitador.<br>
Clase: Kecimen y pasas Besni.</p>
<p><strong>1.Realizar un análisis estadístico descriptivo e inferencial, del conjunto de datos que guistéis de la página</strong></p>
<p><a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggstatsplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>You can cite this package as:
     Patil, I. (2021). Visualizations with statistical details: The 'ggstatsplot' approach.
     Journal of Open Source Software, 6(61), 3167, doi:10.21105/joss.03167</code></pre>
</div>
</div>
<ul>
<li><p><strong>Los datos con los que se trabajara son variedades de pasas Kecimen y Besni cultivadas en Turquía</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar el conjunto de datos desde el archivo "Raisin_Dataset.csv"</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>dattos<span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Raisin_Dataset.csv"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dattos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Area MajorAxisLength MinorAxisLength Eccentricity ConvexArea    Extent
1 87524        442.2460        253.2912    0.8197384      90546 0.7586506
2 75166        406.6907        243.0324    0.8018052      78789 0.6841296
3 90856        442.2670        266.3283    0.7983536      93717 0.6376128
4 45928        286.5406        208.7600    0.6849892      47336 0.6995994
5 79408        352.1908        290.8275    0.5640113      81463 0.7927719
6 49242        318.1254        200.1221    0.7773513      51368 0.6584564
  Perimeter   Class
1  1184.040 Kecimen
2  1121.786 Kecimen
3  1208.575 Kecimen
4   844.162 Kecimen
5  1073.251 Kecimen
6   881.836 Kecimen</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los nombres de las columnas disponibles para poder verificar el nombre de las variables.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">colnames</span>(dattos))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Area"            "MajorAxisLength" "MinorAxisLength" "Eccentricity"   
[5] "ConvexArea"      "Extent"          "Perimeter"       "Class"          </code></pre>
</div>
</div></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Muestra la estructura de los datos y el tipo de cada variable</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dattos) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   900 obs. of  8 variables:
 $ Area           : int  87524 75166 90856 45928 79408 49242 42492 60952 42256 64380 ...
 $ MajorAxisLength: num  442 407 442 287 352 ...
 $ MinorAxisLength: num  253 243 266 209 291 ...
 $ Eccentricity   : num  0.82 0.802 0.798 0.685 0.564 ...
 $ ConvexArea     : int  90546 78789 93717 47336 81463 51368 43904 62329 44743 66125 ...
 $ Extent         : num  0.759 0.684 0.638 0.7 0.793 ...
 $ Perimeter      : num  1184 1122 1209 844 1073 ...
 $ Class          : chr  "Kecimen" "Kecimen" "Kecimen" "Kecimen" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#el número de filas y columnas en un conjunto de datos</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dattos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 900   8</code></pre>
</div>
</div>
<p><strong>Tenemos 900 filas y 8 columnas</strong></p>
<p><strong><em>La función as.factor() sirve para convertir la variable “diagnostico” en un factor.</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dattos<span class="sc">$</span>Class  <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dattos<span class="sc">$</span>Class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Calcular estadísticos descriptivos numéricos</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar el conjunto de datos desde el archivo "cancer.csv"</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Raisin_Dataset.csv"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar las columnas de interés</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>subset_datos <span class="ot">&lt;-</span> datos[, <span class="sc">-</span><span class="fu">ncol</span>(datos)]  <span class="co"># Excluir la última columna</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular estadísticos descriptivos numéricos</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Media =</span> <span class="fu">colMeans</span>(subset_datos),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mediana =</span> <span class="fu">apply</span>(subset_datos, <span class="dv">2</span>, median),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">DesviacionEstandar =</span> <span class="fu">apply</span>(subset_datos, <span class="dv">2</span>, sd),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">ValorMinimo =</span> <span class="fu">apply</span>(subset_datos, <span class="dv">2</span>, min),</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">ValorMaximo =</span> <span class="fu">apply</span>(subset_datos, <span class="dv">2</span>, max)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los estadísticos descriptivos</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Media      Mediana DesviacionEstandar  ValorMinimo
Area            8.780413e+04 78902.000000       3.900211e+04 2.538700e+04
MajorAxisLength 4.309300e+02   407.803951       1.160351e+02 2.256295e+02
MinorAxisLength 2.544881e+02   247.848409       4.998890e+01 1.437109e+02
Eccentricity    7.815422e-01     0.798846       9.031841e-02 3.487296e-01
ConvexArea      9.118609e+04 81651.000000       4.076929e+04 2.613900e+04
Extent          6.995079e-01     0.707367       5.346820e-02 3.798561e-01
Perimeter       1.165907e+03  1119.509000       2.737643e+02 6.190740e+02
                 ValorMaximo
Area            2.350470e+05
MajorAxisLength 9.972919e+02
MinorAxisLength 4.922753e+02
Eccentricity    9.621244e-01
ConvexArea      2.782170e+05
Extent          8.354545e-01
Perimeter       2.697753e+03</code></pre>
</div>
</div>
<p><strong>Existe otra opción para mostrar una estadística descriptiva de los datos y es:</strong></p>
<p><em>La función summary() que mostrará estadísticas como:</em></p>
<ul>
<li><em>El mínimo, el primer cuartil, la mediana, el tercer cuartil y el máximo para cada variable numérica en el conjunto de datos.</em></li>
</ul>
<p><em>Esto nos dará una visión general de la distribución y los valores extremos de cada variable</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticas descriptivas de las variables</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>Area)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  25387   59348   78902   87804  105028  235047 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>MajorAxisLength)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  225.6   345.4   407.8   430.9   494.2   997.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>MinorAxisLength)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  143.7   219.1   247.8   254.5   279.9   492.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>Eccentricity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3487  0.7418  0.7988  0.7815  0.8426  0.9621 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>ConvexArea)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  26139   61513   81651   91186  108376  278217 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>Extent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3799  0.6709  0.7074  0.6995  0.7350  0.8355 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dattos<span class="sc">$</span>Perimeter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  619.1   966.4  1119.5  1165.9  1308.4  2697.8 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribución de las variables categóricas</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dattos<span class="sc">$</span>Class)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Besni Kecimen 
    450     450 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(dattos<span class="sc">$</span>Class)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Besni Kecimen 
    0.5     0.5 </code></pre>
</div>
</div>
<p><strong>Histogramas</strong></p>
<p>Cada gráfico muestra el histograma de los valores de una columna particular, con el color de relleno del histograma basado en la columna Class.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Esta variablecontine todas las variable excepto la última que es Class que se anteriormente la convertimos en Factor.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fu">ncol</span>(dattos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -8</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>l.plots <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">"list"</span>,<span class="at">length =</span> <span class="fu">ncol</span>(dattos)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">ncol</span>(dattos) <span class="sc">-</span><span class="dv">1</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n1){</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  h <span class="ot">&lt;-</span><span class="fu">hist</span>(dattos[,j],<span class="at">plot =</span> F)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  dattos.tmp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value=</span>dattos[,j],<span class="at">Class=</span>dattos<span class="sc">$</span>Class)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dattos.tmp,<span class="fu">aes</span>(value,<span class="at">fill=</span>Class))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">breaks=</span>h<span class="sc">$</span>breaks) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="fu">paste</span>(<span class="st">"Histogram of"</span>, <span class="fu">colnames</span>(dattos)[j]))</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  l.plots[[j]] <span class="ot">&lt;-</span> p1</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong><em>Esta línea de código muestra los histogramas generados anteriormente. Ejecutarlo imprime una lista de histogramas l.plots para cada variable.</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>l.plots</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[5]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[6]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[7]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-9-7.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Calculos de correlacion</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>matriz_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(dattos[, <span class="fu">c</span>(<span class="st">"Area"</span>, <span class="st">"MajorAxisLength"</span>, <span class="st">"MinorAxisLength"</span>, <span class="st">"Eccentricity"</span>, <span class="st">"ConvexArea"</span>, <span class="st">"Extent"</span>, <span class="st">"Perimeter"</span>)])</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar pruebas de correlación </span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>(<span class="fu">ncol</span>(matriz_cor)<span class="sc">-</span><span class="dv">1</span>)) {</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> (i<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span><span class="fu">ncol</span>(matriz_cor)) {</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    cor_test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(dattos[, i], dattos[, j])</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Correlación entre"</span>, <span class="fu">colnames</span>(dattos)[i], <span class="st">"y"</span>, <span class="fu">colnames</span>(dattos)[j]))</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Mostrar correlación</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(cor_test<span class="sc">$</span>estimate)  </span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">"____________________"</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Correlación entre Area y MajorAxisLength"
      cor 
0.9327744 
[1] "____________________"
[1] "Correlación entre Area y MinorAxisLength"
      cor 
0.9066499 
[1] "____________________"
[1] "Correlación entre Area y Eccentricity"
      cor 
0.3361066 
[1] "____________________"
[1] "Correlación entre Area y ConvexArea"
      cor 
0.9959197 
[1] "____________________"
[1] "Correlación entre Area y Extent"
        cor 
-0.01349934 
[1] "____________________"
[1] "Correlación entre Area y Perimeter"
      cor 
0.9613517 
[1] "____________________"
[1] "Correlación entre MajorAxisLength y MinorAxisLength"
      cor 
0.7280302 
[1] "____________________"
[1] "Correlación entre MajorAxisLength y Eccentricity"
      cor 
0.5836084 
[1] "____________________"
[1] "Correlación entre MajorAxisLength y ConvexArea"
      cor 
0.9450309 
[1] "____________________"
[1] "Correlación entre MajorAxisLength y Extent"
       cor 
-0.2038656 
[1] "____________________"
[1] "Correlación entre MajorAxisLength y Perimeter"
     cor 
0.977978 
[1] "____________________"
[1] "Correlación entre MinorAxisLength y Eccentricity"
       cor 
-0.0276835 
[1] "____________________"
[1] "Correlación entre MinorAxisLength y ConvexArea"
      cor 
0.8956513 
[1] "____________________"
[1] "Correlación entre MinorAxisLength y Extent"
      cor 
0.1453215 
[1] "____________________"
[1] "Correlación entre MinorAxisLength y Perimeter"
     cor 
0.827417 
[1] "____________________"
[1] "Correlación entre Eccentricity y ConvexArea"
      cor 
0.3482103 
[1] "____________________"
[1] "Correlación entre Eccentricity y Extent"
       cor 
-0.3610615 
[1] "____________________"
[1] "Correlación entre Eccentricity y Perimeter"
      cor 
0.4478452 
[1] "____________________"
[1] "Correlación entre ConvexArea y Extent"
        cor 
-0.05480247 
[1] "____________________"
[1] "Correlación entre ConvexArea y Perimeter"
      cor 
0.9766122 
[1] "____________________"
[1] "Correlación entre Extent y Perimeter"
       cor 
-0.1734489 
[1] "____________________"</code></pre>
</div>
</div>
<p><strong>Se muestra el resultado en una matriz de correlación con la función corrplot::corrplot().</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>obj.cor <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">corr.test</span>(dattos[,<span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>])</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>p.values <span class="ot">&lt;-</span> obj.cor<span class="sc">$</span>p</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>p.values[<span class="fu">upper.tri</span>(p.values)] <span class="ot">&lt;-</span> obj.cor<span class="sc">$</span>p.adj</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>p.values[<span class="fu">lower.tri</span>(p.values)] <span class="ot">&lt;-</span> obj.cor<span class="sc">$</span>p.adj</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(p.values) <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="at">corr =</span> obj.cor<span class="sc">$</span>r,<span class="at">p.mat =</span> p.values,<span class="at">sig.level =</span> <span class="fl">0.05</span>,<span class="at">insig =</span> <span class="st">"label_sig"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>PCA</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dattos_escalado <span class="ot">&lt;-</span> dattos[, <span class="sc">-</span><span class="fu">ncol</span>(dattos)]  <span class="co"># Excluir la última columna</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>class<span class="ot">&lt;-</span> dattos<span class="sc">$</span>Class</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>dattos_escalado <span class="ot">&lt;-</span> <span class="fu">scale</span>(dattos_escalado)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Calcular PCA</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>pca_resultado <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(dattos_escalado, <span class="at">scale. =</span> <span class="cn">FALSE</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Biplot</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(pca_resultado, <span class="at">main =</span> <span class="st">"Grafico Biplot"</span>)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Los diagnósticos De M y B que sw encuentran en la variable dattos_escalado</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(pca_resultado<span class="sc">$</span>x[class<span class="sc">==</span> <span class="st">"Kecimen"</span>, <span class="dv">1</span>], pca_resultado<span class="sc">$</span>x[class <span class="sc">==</span> <span class="st">"Kecimen"</span>, <span class="dv">2</span>], <span class="at">col =</span> <span class="st">"green"</span>)</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(pca_resultado<span class="sc">$</span>x[class<span class="sc">==</span> <span class="st">"Besni"</span>, <span class="dv">1</span>], pca_resultado<span class="sc">$</span>x[class <span class="sc">==</span> <span class="st">"Besni"</span>, <span class="dv">2</span>], <span class="at">col =</span> <span class="st">"hotpink"</span>)</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Para identificar Kecimen Y Besni segun sus colores, en este caso tenemos Kecimen de verde y Besni de rosado</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Kecimen"</span>, <span class="st">"Besni"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"green"</span>, <span class="st">"hotpink"</span>), <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">title =</span> <span class="st">"Class"</span>, <span class="at">cex =</span> <span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="TenesacaMariuxiAnálisis-de-un-conjunto-de-datos_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca_resultado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3     PC4     PC5     PC6     PC7
Standard deviation     2.1982 1.2055 0.79275 0.23838 0.14768 0.08019 0.03179
Proportion of Variance 0.6903 0.2076 0.08978 0.00812 0.00312 0.00092 0.00014
Cumulative Proportion  0.6903 0.8979 0.98770 0.99582 0.99894 0.99986 1.00000</code></pre>
</div>
</div>
<p><strong>Puede ser de regresión o de clasificación</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Leer el conjunto de datos</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>dattos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Raisin_Dataset.csv"</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la última variable en un factor</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>dattos<span class="sc">$</span>Class <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dattos<span class="sc">$</span>Class)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(dattos<span class="sc">$</span>Class) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"D"</span>,<span class="st">"N"</span>)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Escalar las variables predictoras</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>dattos[, <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(dattos[, <span class="sc">-</span><span class="fu">ncol</span>(dattos)]))</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir los datos en conjunto de entrenamiento y conjunto de prueba</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">createDataPartition</span>(dattos<span class="sc">$</span>Class, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> dattos[train_index, ]</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> dattos[<span class="sc">-</span>train_index, ]</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar un modelo de regresión logística</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>glm_mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(Class <span class="sc">~</span> ., <span class="at">data =</span> train_data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar predicciones en el conjunto de prueba</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(<span class="fu">predict</span>(glm_mod, <span class="at">newdata =</span> test_data, <span class="at">type =</span> <span class="st">"response"</span>) <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="st">"N"</span>, <span class="st">"D"</span>))</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluar el rendimiento del modelo en el conjunto de prueba</span></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>caret<span class="sc">::</span><span class="fu">confusionMatrix</span>(predictions, test_data<span class="sc">$</span>Class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction  D  N
         D 77  8
         N 13 82
                                          
               Accuracy : 0.8833          
                 95% CI : (0.8272, 0.9263)
    No Information Rate : 0.5             
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.7667          
                                          
 Mcnemar's Test P-Value : 0.3827          
                                          
            Sensitivity : 0.8556          
            Specificity : 0.9111          
         Pos Pred Value : 0.9059          
         Neg Pred Value : 0.8632          
             Prevalence : 0.5000          
         Detection Rate : 0.4278          
   Detection Prevalence : 0.4722          
      Balanced Accuracy : 0.8833          
                                          
       'Positive' Class : D               
                                          </code></pre>
</div>
</div>
<p>Evaluación del modelo de regresión logística en el conjunto de datos de pasas.</p>
<p>La precisión del modelo es del 88.33% esto quiere decir que el modelo tiene un buen rendimiento,</p>
<p>La sensibilidad del modelo, que es la proporción de verdaderos positivos, es del 85.56%.</p>
<p>La especificidad del modelo, que es la proporción de verdaderos negativos, es del 91.11%.</p>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>